---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: apache-workbench-tools
  # allow for override: kubectl -n <ns> apply ...
  #namespace: default
spec:
  selector:
    matchLabels:
      app: apache-workbench-tools
  replicas: 1
  template:
    metadata:
      labels:
        app: apache-workbench-tools
      annotations:
        sidecar.istio.io/inject: "false"

    spec:

      containers:
      - name: apache-workbench-tools
        image: ghcr.io/fabianlee/docker-apache-workbench-tools:latest
        args:
        - /bin/sh
        - -c
        - touch /tmp/healthy; date; echo "starting..."; sleep 30d

        # resource limits
        resources:
          requests:
            memory: "8Mi"
            cpu: "500m" # half a vcpu
          limits:
            memory: "16Mi"
            cpu: "1000m" # whole vcpu

        # any environment variables
        env:

        livenessProbe:
          exec:
            command:
            - cat
            - /tmp/healthy
          initialDelaySeconds: 5
          periodSeconds: 5
        readinessProbe:
          exec:
            command:
            - cat
            - /tmp/healthy
          initialDelaySeconds: 5
          periodSeconds: 5

      restartPolicy: Always
